[package]
name = "hacspec-edhoc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexlit = "0.5.3"
hacspec-lib = { path = "../../../Software/hacspec/lib" }
hacspec-sha256 = { path = "../../../Software/hacspec/examples/sha256" }
hacspec-hkdf = { path = "../../../Software/hacspec/examples/hkdf" }
hacspec-aes = { path = "../../../Software/hacspec/examples/aes" }
hacspec-aes-ccm = { path = "../../../Software/hacspec/examples/aes-ccm" }

[lib]
path = "src/edhoc.rs"
